#############################################################################
# Makefile for building: Tetris
# Generated by qmake (3.0) (Qt 5.3.2)
# Project:  Project2.pro
# Template: app
# Command: /usr/local/software/qt5/bin/qmake -o Makefile Project2.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc4
CXX           = g++4
DEFINES       = -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -m64 -pipe -O2 -Wall -W -D_REENTRANT -fPIE $(DEFINES)
CXXFLAGS      = -m64 -pipe -O2 -std=c++0x -Wall -W -D_REENTRANT -fPIE $(DEFINES)
INCPATH       = -I/usr/local/software/qt-5.3.2/mkspecs/linux-g++-64 -I. -I/usr/local/software/qt-5.3.2/include -I/usr/local/software/qt-5.3.2/include/QtWidgets -I/usr/local/software/qt-5.3.2/include/QtGui -I/usr/local/software/qt-5.3.2/include/QtCore -I.
LINK          = g++4
LFLAGS        = -m64 -Wl,-O1 -Wl,-rpath,/usr/local/software/qt5/lib -Wl,-rpath,/usr/local/software/qt-5.3.2/lib
LIBS          = $(SUBLIBS) -L/usr/X11R6/lib64 -L/usr/local/software/qt-5.3.2/lib -lQt5Widgets -Wl,-rpath,/usr/local/lib -L/usr/local/lib -Wl,-rpath,/usr/local/lib -lQt5Gui -Wl,-rpath,/usr/local/lib -lQt5Core -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/local/software/qt5/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		TetrisBlocks.cpp \
		TetrisGame.cpp \
		TetrisWindow.cpp 
OBJECTS       = main.o \
		TetrisBlocks.o \
		TetrisGame.o \
		TetrisWindow.o
DIST          = /usr/local/software/qt-5.3.2/mkspecs/features/spec_pre.prf \
		/usr/local/software/qt-5.3.2/mkspecs/common/shell-unix.conf \
		/usr/local/software/qt-5.3.2/mkspecs/common/unix.conf \
		/usr/local/software/qt-5.3.2/mkspecs/common/linux.conf \
		/usr/local/software/qt-5.3.2/mkspecs/common/gcc-base.conf \
		/usr/local/software/qt-5.3.2/mkspecs/common/gcc-base-unix.conf \
		/usr/local/software/qt-5.3.2/mkspecs/common/g++-base.conf \
		/usr/local/software/qt-5.3.2/mkspecs/common/g++-unix.conf \
		/usr/local/software/qt-5.3.2/mkspecs/qconfig.pri \
		/usr/local/software/qt-5.3.2/mkspecs/modules/qt_lib_bluetooth.pri \
		/usr/local/software/qt-5.3.2/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/usr/local/software/qt-5.3.2/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/local/software/qt-5.3.2/mkspecs/modules/qt_lib_clucene_private.pri \
		/usr/local/software/qt-5.3.2/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/local/software/qt-5.3.2/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/local/software/qt-5.3.2/mkspecs/modules/qt_lib_core.pri \
		/usr/local/software/qt-5.3.2/mkspecs/modules/qt_lib_core_private.pri \
		/usr/local/software/qt-5.3.2/mkspecs/modules/qt_lib_dbus.pri \
		/usr/local/software/qt-5.3.2/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/local/software/qt-5.3.2/mkspecs/modules/qt_lib_declarative.pri \
		/usr/local/software/qt-5.3.2/mkspecs/modules/qt_lib_declarative_private.pri \
		/usr/local/software/qt-5.3.2/mkspecs/modules/qt_lib_designer.pri \
		/usr/local/software/qt-5.3.2/mkspecs/modules/qt_lib_designer_private.pri \
		/usr/local/software/qt-5.3.2/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/usr/local/software/qt-5.3.2/mkspecs/modules/qt_lib_enginio.pri \
		/usr/local/software/qt-5.3.2/mkspecs/modules/qt_lib_enginio_private.pri \
		/usr/local/software/qt-5.3.2/mkspecs/modules/qt_lib_gui.pri \
		/usr/local/software/qt-5.3.2/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/local/software/qt-5.3.2/mkspecs/modules/qt_lib_help.pri \
		/usr/local/software/qt-5.3.2/mkspecs/modules/qt_lib_help_private.pri \
		/usr/local/software/qt-5.3.2/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/local/software/qt-5.3.2/mkspecs/modules/qt_lib_multimedia_private.pri \
		/usr/local/software/qt-5.3.2/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/local/software/qt-5.3.2/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/usr/local/software/qt-5.3.2/mkspecs/modules/qt_lib_network.pri \
		/usr/local/software/qt-5.3.2/mkspecs/modules/qt_lib_network_private.pri \
		/usr/local/software/qt-5.3.2/mkspecs/modules/qt_lib_nfc.pri \
		/usr/local/software/qt-5.3.2/mkspecs/modules/qt_lib_nfc_private.pri \
		/usr/local/software/qt-5.3.2/mkspecs/modules/qt_lib_opengl.pri \
		/usr/local/software/qt-5.3.2/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/local/software/qt-5.3.2/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/local/software/qt-5.3.2/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/local/software/qt-5.3.2/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/usr/local/software/qt-5.3.2/mkspecs/modules/qt_lib_positioning.pri \
		/usr/local/software/qt-5.3.2/mkspecs/modules/qt_lib_positioning_private.pri \
		/usr/local/software/qt-5.3.2/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/local/software/qt-5.3.2/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/local/software/qt-5.3.2/mkspecs/modules/qt_lib_qml.pri \
		/usr/local/software/qt-5.3.2/mkspecs/modules/qt_lib_qml_private.pri \
		/usr/local/software/qt-5.3.2/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/usr/local/software/qt-5.3.2/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/local/software/qt-5.3.2/mkspecs/modules/qt_lib_qmltest_private.pri \
		/usr/local/software/qt-5.3.2/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/usr/local/software/qt-5.3.2/mkspecs/modules/qt_lib_quick.pri \
		/usr/local/software/qt-5.3.2/mkspecs/modules/qt_lib_quick_private.pri \
		/usr/local/software/qt-5.3.2/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/usr/local/software/qt-5.3.2/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/local/software/qt-5.3.2/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/usr/local/software/qt-5.3.2/mkspecs/modules/qt_lib_script.pri \
		/usr/local/software/qt-5.3.2/mkspecs/modules/qt_lib_script_private.pri \
		/usr/local/software/qt-5.3.2/mkspecs/modules/qt_lib_scripttools.pri \
		/usr/local/software/qt-5.3.2/mkspecs/modules/qt_lib_scripttools_private.pri \
		/usr/local/software/qt-5.3.2/mkspecs/modules/qt_lib_sensors.pri \
		/usr/local/software/qt-5.3.2/mkspecs/modules/qt_lib_sensors_private.pri \
		/usr/local/software/qt-5.3.2/mkspecs/modules/qt_lib_serialport.pri \
		/usr/local/software/qt-5.3.2/mkspecs/modules/qt_lib_serialport_private.pri \
		/usr/local/software/qt-5.3.2/mkspecs/modules/qt_lib_sql.pri \
		/usr/local/software/qt-5.3.2/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/local/software/qt-5.3.2/mkspecs/modules/qt_lib_svg.pri \
		/usr/local/software/qt-5.3.2/mkspecs/modules/qt_lib_svg_private.pri \
		/usr/local/software/qt-5.3.2/mkspecs/modules/qt_lib_testlib.pri \
		/usr/local/software/qt-5.3.2/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/local/software/qt-5.3.2/mkspecs/modules/qt_lib_uitools.pri \
		/usr/local/software/qt-5.3.2/mkspecs/modules/qt_lib_uitools_private.pri \
		/usr/local/software/qt-5.3.2/mkspecs/modules/qt_lib_websockets.pri \
		/usr/local/software/qt-5.3.2/mkspecs/modules/qt_lib_websockets_private.pri \
		/usr/local/software/qt-5.3.2/mkspecs/modules/qt_lib_widgets.pri \
		/usr/local/software/qt-5.3.2/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/local/software/qt-5.3.2/mkspecs/modules/qt_lib_x11extras.pri \
		/usr/local/software/qt-5.3.2/mkspecs/modules/qt_lib_x11extras_private.pri \
		/usr/local/software/qt-5.3.2/mkspecs/modules/qt_lib_xml.pri \
		/usr/local/software/qt-5.3.2/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/local/software/qt-5.3.2/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/usr/local/software/qt-5.3.2/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/usr/local/software/qt-5.3.2/mkspecs/features/qt_functions.prf \
		/usr/local/software/qt-5.3.2/mkspecs/features/qt_config.prf \
		/usr/local/software/qt-5.3.2/mkspecs/linux-g++-64/qmake.conf \
		/usr/local/software/qt-5.3.2/mkspecs/features/spec_post.prf \
		/usr/local/software/qt-5.3.2/mkspecs/features/exclusive_builds.prf \
		/usr/local/software/qt-5.3.2/mkspecs/features/default_pre.prf \
		/usr/local/software/qt-5.3.2/mkspecs/features/resolve_config.prf \
		/usr/local/software/qt-5.3.2/mkspecs/features/default_post.prf \
		/usr/local/software/qt-5.3.2/mkspecs/features/c++11.prf \
		/usr/local/software/qt-5.3.2/mkspecs/features/warn_on.prf \
		/usr/local/software/qt-5.3.2/mkspecs/features/qt.prf \
		/usr/local/software/qt-5.3.2/mkspecs/features/resources.prf \
		/usr/local/software/qt-5.3.2/mkspecs/features/moc.prf \
		/usr/local/software/qt-5.3.2/mkspecs/features/unix/opengl.prf \
		/usr/local/software/qt-5.3.2/mkspecs/features/uic.prf \
		/usr/local/software/qt-5.3.2/mkspecs/features/unix/thread.prf \
		/usr/local/software/qt-5.3.2/mkspecs/features/testcase_targets.prf \
		/usr/local/software/qt-5.3.2/mkspecs/features/exceptions.prf \
		/usr/local/software/qt-5.3.2/mkspecs/features/yacc.prf \
		/usr/local/software/qt-5.3.2/mkspecs/features/lex.prf \
		Project2.pro main.cpp \
		TetrisBlocks.cpp \
		TetrisGame.cpp \
		TetrisWindow.cpp
QMAKE_TARGET  = Tetris
DESTDIR       = #avoid trailing-slash linebreak
TARGET        = Tetris


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: Project2.pro /usr/local/software/qt-5.3.2/mkspecs/linux-g++-64/qmake.conf /usr/local/software/qt-5.3.2/mkspecs/features/spec_pre.prf \
		/usr/local/software/qt-5.3.2/mkspecs/common/shell-unix.conf \
		/usr/local/software/qt-5.3.2/mkspecs/common/unix.conf \
		/usr/local/software/qt-5.3.2/mkspecs/common/linux.conf \
		/usr/local/software/qt-5.3.2/mkspecs/common/gcc-base.conf \
		/usr/local/software/qt-5.3.2/mkspecs/common/gcc-base-unix.conf \
		/usr/local/software/qt-5.3.2/mkspecs/common/g++-base.conf \
		/usr/local/software/qt-5.3.2/mkspecs/common/g++-unix.conf \
		/usr/local/software/qt-5.3.2/mkspecs/qconfig.pri \
		/usr/local/software/qt-5.3.2/mkspecs/modules/qt_lib_bluetooth.pri \
		/usr/local/software/qt-5.3.2/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/usr/local/software/qt-5.3.2/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/local/software/qt-5.3.2/mkspecs/modules/qt_lib_clucene_private.pri \
		/usr/local/software/qt-5.3.2/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/local/software/qt-5.3.2/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/local/software/qt-5.3.2/mkspecs/modules/qt_lib_core.pri \
		/usr/local/software/qt-5.3.2/mkspecs/modules/qt_lib_core_private.pri \
		/usr/local/software/qt-5.3.2/mkspecs/modules/qt_lib_dbus.pri \
		/usr/local/software/qt-5.3.2/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/local/software/qt-5.3.2/mkspecs/modules/qt_lib_declarative.pri \
		/usr/local/software/qt-5.3.2/mkspecs/modules/qt_lib_declarative_private.pri \
		/usr/local/software/qt-5.3.2/mkspecs/modules/qt_lib_designer.pri \
		/usr/local/software/qt-5.3.2/mkspecs/modules/qt_lib_designer_private.pri \
		/usr/local/software/qt-5.3.2/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/usr/local/software/qt-5.3.2/mkspecs/modules/qt_lib_enginio.pri \
		/usr/local/software/qt-5.3.2/mkspecs/modules/qt_lib_enginio_private.pri \
		/usr/local/software/qt-5.3.2/mkspecs/modules/qt_lib_gui.pri \
		/usr/local/software/qt-5.3.2/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/local/software/qt-5.3.2/mkspecs/modules/qt_lib_help.pri \
		/usr/local/software/qt-5.3.2/mkspecs/modules/qt_lib_help_private.pri \
		/usr/local/software/qt-5.3.2/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/local/software/qt-5.3.2/mkspecs/modules/qt_lib_multimedia_private.pri \
		/usr/local/software/qt-5.3.2/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/local/software/qt-5.3.2/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/usr/local/software/qt-5.3.2/mkspecs/modules/qt_lib_network.pri \
		/usr/local/software/qt-5.3.2/mkspecs/modules/qt_lib_network_private.pri \
		/usr/local/software/qt-5.3.2/mkspecs/modules/qt_lib_nfc.pri \
		/usr/local/software/qt-5.3.2/mkspecs/modules/qt_lib_nfc_private.pri \
		/usr/local/software/qt-5.3.2/mkspecs/modules/qt_lib_opengl.pri \
		/usr/local/software/qt-5.3.2/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/local/software/qt-5.3.2/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/local/software/qt-5.3.2/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/local/software/qt-5.3.2/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/usr/local/software/qt-5.3.2/mkspecs/modules/qt_lib_positioning.pri \
		/usr/local/software/qt-5.3.2/mkspecs/modules/qt_lib_positioning_private.pri \
		/usr/local/software/qt-5.3.2/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/local/software/qt-5.3.2/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/local/software/qt-5.3.2/mkspecs/modules/qt_lib_qml.pri \
		/usr/local/software/qt-5.3.2/mkspecs/modules/qt_lib_qml_private.pri \
		/usr/local/software/qt-5.3.2/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/usr/local/software/qt-5.3.2/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/local/software/qt-5.3.2/mkspecs/modules/qt_lib_qmltest_private.pri \
		/usr/local/software/qt-5.3.2/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/usr/local/software/qt-5.3.2/mkspecs/modules/qt_lib_quick.pri \
		/usr/local/software/qt-5.3.2/mkspecs/modules/qt_lib_quick_private.pri \
		/usr/local/software/qt-5.3.2/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/usr/local/software/qt-5.3.2/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/local/software/qt-5.3.2/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/usr/local/software/qt-5.3.2/mkspecs/modules/qt_lib_script.pri \
		/usr/local/software/qt-5.3.2/mkspecs/modules/qt_lib_script_private.pri \
		/usr/local/software/qt-5.3.2/mkspecs/modules/qt_lib_scripttools.pri \
		/usr/local/software/qt-5.3.2/mkspecs/modules/qt_lib_scripttools_private.pri \
		/usr/local/software/qt-5.3.2/mkspecs/modules/qt_lib_sensors.pri \
		/usr/local/software/qt-5.3.2/mkspecs/modules/qt_lib_sensors_private.pri \
		/usr/local/software/qt-5.3.2/mkspecs/modules/qt_lib_serialport.pri \
		/usr/local/software/qt-5.3.2/mkspecs/modules/qt_lib_serialport_private.pri \
		/usr/local/software/qt-5.3.2/mkspecs/modules/qt_lib_sql.pri \
		/usr/local/software/qt-5.3.2/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/local/software/qt-5.3.2/mkspecs/modules/qt_lib_svg.pri \
		/usr/local/software/qt-5.3.2/mkspecs/modules/qt_lib_svg_private.pri \
		/usr/local/software/qt-5.3.2/mkspecs/modules/qt_lib_testlib.pri \
		/usr/local/software/qt-5.3.2/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/local/software/qt-5.3.2/mkspecs/modules/qt_lib_uitools.pri \
		/usr/local/software/qt-5.3.2/mkspecs/modules/qt_lib_uitools_private.pri \
		/usr/local/software/qt-5.3.2/mkspecs/modules/qt_lib_websockets.pri \
		/usr/local/software/qt-5.3.2/mkspecs/modules/qt_lib_websockets_private.pri \
		/usr/local/software/qt-5.3.2/mkspecs/modules/qt_lib_widgets.pri \
		/usr/local/software/qt-5.3.2/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/local/software/qt-5.3.2/mkspecs/modules/qt_lib_x11extras.pri \
		/usr/local/software/qt-5.3.2/mkspecs/modules/qt_lib_x11extras_private.pri \
		/usr/local/software/qt-5.3.2/mkspecs/modules/qt_lib_xml.pri \
		/usr/local/software/qt-5.3.2/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/local/software/qt-5.3.2/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/usr/local/software/qt-5.3.2/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/usr/local/software/qt-5.3.2/mkspecs/features/qt_functions.prf \
		/usr/local/software/qt-5.3.2/mkspecs/features/qt_config.prf \
		/usr/local/software/qt-5.3.2/mkspecs/linux-g++-64/qmake.conf \
		/usr/local/software/qt-5.3.2/mkspecs/features/spec_post.prf \
		/usr/local/software/qt-5.3.2/mkspecs/features/exclusive_builds.prf \
		/usr/local/software/qt-5.3.2/mkspecs/features/default_pre.prf \
		/usr/local/software/qt-5.3.2/mkspecs/features/resolve_config.prf \
		/usr/local/software/qt-5.3.2/mkspecs/features/default_post.prf \
		/usr/local/software/qt-5.3.2/mkspecs/features/c++11.prf \
		/usr/local/software/qt-5.3.2/mkspecs/features/warn_on.prf \
		/usr/local/software/qt-5.3.2/mkspecs/features/qt.prf \
		/usr/local/software/qt-5.3.2/mkspecs/features/resources.prf \
		/usr/local/software/qt-5.3.2/mkspecs/features/moc.prf \
		/usr/local/software/qt-5.3.2/mkspecs/features/unix/opengl.prf \
		/usr/local/software/qt-5.3.2/mkspecs/features/uic.prf \
		/usr/local/software/qt-5.3.2/mkspecs/features/unix/thread.prf \
		/usr/local/software/qt-5.3.2/mkspecs/features/testcase_targets.prf \
		/usr/local/software/qt-5.3.2/mkspecs/features/exceptions.prf \
		/usr/local/software/qt-5.3.2/mkspecs/features/yacc.prf \
		/usr/local/software/qt-5.3.2/mkspecs/features/lex.prf \
		Project2.pro \
		/usr/local/software/qt-5.3.2/lib/libQt5Widgets.prl \
		/usr/local/software/qt-5.3.2/lib/libQt5Gui.prl \
		/usr/local/software/qt-5.3.2/lib/libQt5Core.prl
	$(QMAKE) -o Makefile Project2.pro
/usr/local/software/qt-5.3.2/mkspecs/features/spec_pre.prf:
/usr/local/software/qt-5.3.2/mkspecs/common/shell-unix.conf:
/usr/local/software/qt-5.3.2/mkspecs/common/unix.conf:
/usr/local/software/qt-5.3.2/mkspecs/common/linux.conf:
/usr/local/software/qt-5.3.2/mkspecs/common/gcc-base.conf:
/usr/local/software/qt-5.3.2/mkspecs/common/gcc-base-unix.conf:
/usr/local/software/qt-5.3.2/mkspecs/common/g++-base.conf:
/usr/local/software/qt-5.3.2/mkspecs/common/g++-unix.conf:
/usr/local/software/qt-5.3.2/mkspecs/qconfig.pri:
/usr/local/software/qt-5.3.2/mkspecs/modules/qt_lib_bluetooth.pri:
/usr/local/software/qt-5.3.2/mkspecs/modules/qt_lib_bluetooth_private.pri:
/usr/local/software/qt-5.3.2/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/local/software/qt-5.3.2/mkspecs/modules/qt_lib_clucene_private.pri:
/usr/local/software/qt-5.3.2/mkspecs/modules/qt_lib_concurrent.pri:
/usr/local/software/qt-5.3.2/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/local/software/qt-5.3.2/mkspecs/modules/qt_lib_core.pri:
/usr/local/software/qt-5.3.2/mkspecs/modules/qt_lib_core_private.pri:
/usr/local/software/qt-5.3.2/mkspecs/modules/qt_lib_dbus.pri:
/usr/local/software/qt-5.3.2/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/local/software/qt-5.3.2/mkspecs/modules/qt_lib_declarative.pri:
/usr/local/software/qt-5.3.2/mkspecs/modules/qt_lib_declarative_private.pri:
/usr/local/software/qt-5.3.2/mkspecs/modules/qt_lib_designer.pri:
/usr/local/software/qt-5.3.2/mkspecs/modules/qt_lib_designer_private.pri:
/usr/local/software/qt-5.3.2/mkspecs/modules/qt_lib_designercomponents_private.pri:
/usr/local/software/qt-5.3.2/mkspecs/modules/qt_lib_enginio.pri:
/usr/local/software/qt-5.3.2/mkspecs/modules/qt_lib_enginio_private.pri:
/usr/local/software/qt-5.3.2/mkspecs/modules/qt_lib_gui.pri:
/usr/local/software/qt-5.3.2/mkspecs/modules/qt_lib_gui_private.pri:
/usr/local/software/qt-5.3.2/mkspecs/modules/qt_lib_help.pri:
/usr/local/software/qt-5.3.2/mkspecs/modules/qt_lib_help_private.pri:
/usr/local/software/qt-5.3.2/mkspecs/modules/qt_lib_multimedia.pri:
/usr/local/software/qt-5.3.2/mkspecs/modules/qt_lib_multimedia_private.pri:
/usr/local/software/qt-5.3.2/mkspecs/modules/qt_lib_multimediawidgets.pri:
/usr/local/software/qt-5.3.2/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/usr/local/software/qt-5.3.2/mkspecs/modules/qt_lib_network.pri:
/usr/local/software/qt-5.3.2/mkspecs/modules/qt_lib_network_private.pri:
/usr/local/software/qt-5.3.2/mkspecs/modules/qt_lib_nfc.pri:
/usr/local/software/qt-5.3.2/mkspecs/modules/qt_lib_nfc_private.pri:
/usr/local/software/qt-5.3.2/mkspecs/modules/qt_lib_opengl.pri:
/usr/local/software/qt-5.3.2/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/local/software/qt-5.3.2/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/local/software/qt-5.3.2/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/local/software/qt-5.3.2/mkspecs/modules/qt_lib_platformsupport_private.pri:
/usr/local/software/qt-5.3.2/mkspecs/modules/qt_lib_positioning.pri:
/usr/local/software/qt-5.3.2/mkspecs/modules/qt_lib_positioning_private.pri:
/usr/local/software/qt-5.3.2/mkspecs/modules/qt_lib_printsupport.pri:
/usr/local/software/qt-5.3.2/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/local/software/qt-5.3.2/mkspecs/modules/qt_lib_qml.pri:
/usr/local/software/qt-5.3.2/mkspecs/modules/qt_lib_qml_private.pri:
/usr/local/software/qt-5.3.2/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/usr/local/software/qt-5.3.2/mkspecs/modules/qt_lib_qmltest.pri:
/usr/local/software/qt-5.3.2/mkspecs/modules/qt_lib_qmltest_private.pri:
/usr/local/software/qt-5.3.2/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
/usr/local/software/qt-5.3.2/mkspecs/modules/qt_lib_quick.pri:
/usr/local/software/qt-5.3.2/mkspecs/modules/qt_lib_quick_private.pri:
/usr/local/software/qt-5.3.2/mkspecs/modules/qt_lib_quickparticles_private.pri:
/usr/local/software/qt-5.3.2/mkspecs/modules/qt_lib_quickwidgets.pri:
/usr/local/software/qt-5.3.2/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/usr/local/software/qt-5.3.2/mkspecs/modules/qt_lib_script.pri:
/usr/local/software/qt-5.3.2/mkspecs/modules/qt_lib_script_private.pri:
/usr/local/software/qt-5.3.2/mkspecs/modules/qt_lib_scripttools.pri:
/usr/local/software/qt-5.3.2/mkspecs/modules/qt_lib_scripttools_private.pri:
/usr/local/software/qt-5.3.2/mkspecs/modules/qt_lib_sensors.pri:
/usr/local/software/qt-5.3.2/mkspecs/modules/qt_lib_sensors_private.pri:
/usr/local/software/qt-5.3.2/mkspecs/modules/qt_lib_serialport.pri:
/usr/local/software/qt-5.3.2/mkspecs/modules/qt_lib_serialport_private.pri:
/usr/local/software/qt-5.3.2/mkspecs/modules/qt_lib_sql.pri:
/usr/local/software/qt-5.3.2/mkspecs/modules/qt_lib_sql_private.pri:
/usr/local/software/qt-5.3.2/mkspecs/modules/qt_lib_svg.pri:
/usr/local/software/qt-5.3.2/mkspecs/modules/qt_lib_svg_private.pri:
/usr/local/software/qt-5.3.2/mkspecs/modules/qt_lib_testlib.pri:
/usr/local/software/qt-5.3.2/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/local/software/qt-5.3.2/mkspecs/modules/qt_lib_uitools.pri:
/usr/local/software/qt-5.3.2/mkspecs/modules/qt_lib_uitools_private.pri:
/usr/local/software/qt-5.3.2/mkspecs/modules/qt_lib_websockets.pri:
/usr/local/software/qt-5.3.2/mkspecs/modules/qt_lib_websockets_private.pri:
/usr/local/software/qt-5.3.2/mkspecs/modules/qt_lib_widgets.pri:
/usr/local/software/qt-5.3.2/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/local/software/qt-5.3.2/mkspecs/modules/qt_lib_x11extras.pri:
/usr/local/software/qt-5.3.2/mkspecs/modules/qt_lib_x11extras_private.pri:
/usr/local/software/qt-5.3.2/mkspecs/modules/qt_lib_xml.pri:
/usr/local/software/qt-5.3.2/mkspecs/modules/qt_lib_xml_private.pri:
/usr/local/software/qt-5.3.2/mkspecs/modules/qt_lib_xmlpatterns.pri:
/usr/local/software/qt-5.3.2/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/usr/local/software/qt-5.3.2/mkspecs/features/qt_functions.prf:
/usr/local/software/qt-5.3.2/mkspecs/features/qt_config.prf:
/usr/local/software/qt-5.3.2/mkspecs/linux-g++-64/qmake.conf:
/usr/local/software/qt-5.3.2/mkspecs/features/spec_post.prf:
/usr/local/software/qt-5.3.2/mkspecs/features/exclusive_builds.prf:
/usr/local/software/qt-5.3.2/mkspecs/features/default_pre.prf:
/usr/local/software/qt-5.3.2/mkspecs/features/resolve_config.prf:
/usr/local/software/qt-5.3.2/mkspecs/features/default_post.prf:
/usr/local/software/qt-5.3.2/mkspecs/features/c++11.prf:
/usr/local/software/qt-5.3.2/mkspecs/features/warn_on.prf:
/usr/local/software/qt-5.3.2/mkspecs/features/qt.prf:
/usr/local/software/qt-5.3.2/mkspecs/features/resources.prf:
/usr/local/software/qt-5.3.2/mkspecs/features/moc.prf:
/usr/local/software/qt-5.3.2/mkspecs/features/unix/opengl.prf:
/usr/local/software/qt-5.3.2/mkspecs/features/uic.prf:
/usr/local/software/qt-5.3.2/mkspecs/features/unix/thread.prf:
/usr/local/software/qt-5.3.2/mkspecs/features/testcase_targets.prf:
/usr/local/software/qt-5.3.2/mkspecs/features/exceptions.prf:
/usr/local/software/qt-5.3.2/mkspecs/features/yacc.prf:
/usr/local/software/qt-5.3.2/mkspecs/features/lex.prf:
Project2.pro:
/usr/local/software/qt-5.3.2/lib/libQt5Widgets.prl:
/usr/local/software/qt-5.3.2/lib/libQt5Gui.prl:
/usr/local/software/qt-5.3.2/lib/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile Project2.pro

qmake_all: FORCE

dist: 
	@test -d .tmp/Tetris1.0.0 || mkdir -p .tmp/Tetris1.0.0
	$(COPY_FILE) --parents $(DIST) .tmp/Tetris1.0.0/ && $(COPY_FILE) --parents TetrisBlocks.h TetrisGame.h TetrisWindow.h .tmp/Tetris1.0.0/ && $(COPY_FILE) --parents main.cpp TetrisBlocks.cpp TetrisGame.cpp TetrisWindow.cpp .tmp/Tetris1.0.0/ && (cd `dirname .tmp/Tetris1.0.0` && $(TAR) Tetris1.0.0.tar Tetris1.0.0 && $(COMPRESS) Tetris1.0.0.tar) && $(MOVE) `dirname .tmp/Tetris1.0.0`/Tetris1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/Tetris1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_header_make_all:
compiler_moc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: 

####### Compile

main.o: main.cpp /usr/local/software/qt-5.3.2/include/QtWidgets/QApplication \
		/usr/local/software/qt-5.3.2/include/QtWidgets/qapplication.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qcoreapplication.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qglobal.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qconfig.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qfeatures.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qsystemdetection.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qprocessordetection.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qcompilerdetection.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qtypeinfo.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qtypetraits.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qsysinfo.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qlogging.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qflags.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qatomic.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qbasicatomic.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qatomic_bootstrap.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qgenericatomic.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qatomic_msvc.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qatomic_armv7.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qatomic_armv6.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qatomic_armv5.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qatomic_ia64.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qatomic_mips.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qatomic_x86.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qatomic_cxx11.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qatomic_gcc.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qatomic_unix.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qglobalstatic.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qmutex.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qnumeric.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qstring.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qchar.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qbytearray.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qrefcount.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qnamespace.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qarraydata.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qstringbuilder.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qobject.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qobjectdefs.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qobjectdefs_impl.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qlist.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qalgorithms.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qiterator.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qcoreevent.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qscopedpointer.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qmetatype.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qvarlengtharray.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qcontainerfwd.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qisenum.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qobject_impl.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qeventloop.h \
		/usr/local/software/qt-5.3.2/include/QtGui/qwindowdefs.h \
		/usr/local/software/qt-5.3.2/include/QtGui/qwindowdefs_win.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qpoint.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qsize.h \
		/usr/local/software/qt-5.3.2/include/QtGui/qcursor.h \
		/usr/local/software/qt-5.3.2/include/QtWidgets/qdesktopwidget.h \
		/usr/local/software/qt-5.3.2/include/QtWidgets/qwidget.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qmargins.h \
		/usr/local/software/qt-5.3.2/include/QtGui/qpaintdevice.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qrect.h \
		/usr/local/software/qt-5.3.2/include/QtGui/qpalette.h \
		/usr/local/software/qt-5.3.2/include/QtGui/qcolor.h \
		/usr/local/software/qt-5.3.2/include/QtGui/qrgb.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qstringlist.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qdatastream.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qiodevice.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qpair.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qregexp.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qstringmatcher.h \
		/usr/local/software/qt-5.3.2/include/QtGui/qbrush.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qvector.h \
		/usr/local/software/qt-5.3.2/include/QtGui/qmatrix.h \
		/usr/local/software/qt-5.3.2/include/QtGui/qpolygon.h \
		/usr/local/software/qt-5.3.2/include/QtGui/qregion.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qline.h \
		/usr/local/software/qt-5.3.2/include/QtGui/qtransform.h \
		/usr/local/software/qt-5.3.2/include/QtGui/qpainterpath.h \
		/usr/local/software/qt-5.3.2/include/QtGui/qimage.h \
		/usr/local/software/qt-5.3.2/include/QtGui/qpixmap.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qsharedpointer.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qshareddata.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qsharedpointer_impl.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qhash.h \
		/usr/local/software/qt-5.3.2/include/QtGui/qfont.h \
		/usr/local/software/qt-5.3.2/include/QtGui/qfontmetrics.h \
		/usr/local/software/qt-5.3.2/include/QtGui/qfontinfo.h \
		/usr/local/software/qt-5.3.2/include/QtWidgets/qsizepolicy.h \
		/usr/local/software/qt-5.3.2/include/QtGui/qkeysequence.h \
		/usr/local/software/qt-5.3.2/include/QtGui/qevent.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qvariant.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qmap.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qdebug.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qtextstream.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qlocale.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qset.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qcontiguouscache.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qurl.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qurlquery.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qfile.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qfiledevice.h \
		/usr/local/software/qt-5.3.2/include/QtGui/qvector2d.h \
		/usr/local/software/qt-5.3.2/include/QtGui/qtouchdevice.h \
		/usr/local/software/qt-5.3.2/include/QtGui/qguiapplication.h \
		/usr/local/software/qt-5.3.2/include/QtGui/qinputmethod.h \
		TetrisWindow.h \
		/usr/local/software/qt-5.3.2/include/QtWidgets/QWidget \
		/usr/local/software/qt-5.3.2/include/QtWidgets/QGridLayout \
		/usr/local/software/qt-5.3.2/include/QtWidgets/qgridlayout.h \
		/usr/local/software/qt-5.3.2/include/QtWidgets/qlayout.h \
		/usr/local/software/qt-5.3.2/include/QtWidgets/qlayoutitem.h \
		/usr/local/software/qt-5.3.2/include/QtWidgets/qboxlayout.h \
		/usr/local/software/qt-5.3.2/include/QtGui/QKeyEvent \
		/usr/local/software/qt-5.3.2/include/QtGui/QPainter \
		/usr/local/software/qt-5.3.2/include/QtGui/qpainter.h \
		/usr/local/software/qt-5.3.2/include/QtGui/qtextoption.h \
		/usr/local/software/qt-5.3.2/include/QtGui/qpen.h \
		/usr/local/software/qt-5.3.2/include/QtWidgets/QLabel \
		/usr/local/software/qt-5.3.2/include/QtWidgets/qlabel.h \
		/usr/local/software/qt-5.3.2/include/QtWidgets/qframe.h \
		/usr/local/software/qt-5.3.2/include/QtCore/QBasicTimer \
		/usr/local/software/qt-5.3.2/include/QtCore/qbasictimer.h \
		/usr/local/software/qt-5.3.2/include/QtCore/QString \
		TetrisGame.h \
		/usr/local/software/qt-5.3.2/include/QtCore/QtCore \
		/usr/local/software/qt-5.3.2/include/QtCore/QtCoreDepends \
		/usr/local/software/qt-5.3.2/include/QtCore/qabstractanimation.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qanimationgroup.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qparallelanimationgroup.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qpauseanimation.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qpropertyanimation.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qvariantanimation.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qeasingcurve.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qsequentialanimationgroup.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qtextcodec.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qendian.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qlibraryinfo.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qdatetime.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qbuffer.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qdir.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qfileinfo.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qdiriterator.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qfileselector.h \
		/usr/local/software/qt-5.3.2/include/QtCore/QObject \
		/usr/local/software/qt-5.3.2/include/QtCore/QStringList \
		/usr/local/software/qt-5.3.2/include/QtCore/qfilesystemwatcher.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qlockfile.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qloggingcategory.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qprocess.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qresource.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qsavefile.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qsettings.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qstandardpaths.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qtemporarydir.h \
		/usr/local/software/qt-5.3.2/include/QtCore/QScopedPointer \
		/usr/local/software/qt-5.3.2/include/QtCore/qtemporaryfile.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qabstractitemmodel.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qabstractproxymodel.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qidentityproxymodel.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qitemselectionmodel.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qsortfilterproxymodel.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qstringlistmodel.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qjsonarray.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qjsonvalue.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qjsondocument.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qjsonobject.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qabstracteventdispatcher.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qabstractnativeeventfilter.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qmath.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qmetaobject.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qmimedata.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qobjectcleanuphandler.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qpointer.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qsharedmemory.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qsignalmapper.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qsocketnotifier.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qsystemsemaphore.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qtimer.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qtranslator.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qwineventnotifier.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qmimedatabase.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qmimetype.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qfactoryinterface.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qlibrary.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qplugin.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qpluginloader.h \
		/usr/local/software/qt-5.3.2/include/QtCore/quuid.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qabstractstate.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qabstracttransition.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qeventtransition.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qfinalstate.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qhistorystate.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qsignaltransition.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qstate.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qstatemachine.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qexception.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qfuture.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qfutureinterface.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qrunnable.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qresultstore.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qfuturesynchronizer.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qfuturewatcher.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qreadwritelock.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qsemaphore.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qthread.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qthreadpool.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qthreadstorage.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qwaitcondition.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qarraydataops.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qarraydatapointer.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qbitarray.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qbytearraymatcher.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qcache.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qcollator.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qcommandlineoption.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qcommandlineparser.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qcryptographichash.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qelapsedtimer.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qlinkedlist.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qmessageauthenticationcode.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qqueue.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qregularexpression.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qscopedvaluerollback.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qstack.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qtextboundaryfinder.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qtimeline.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qtimezone.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qxmlstream.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qtcoreversion.h \
		TetrisBlocks.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

TetrisBlocks.o: TetrisBlocks.cpp TetrisBlocks.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qnamespace.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qglobal.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qconfig.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qfeatures.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qsystemdetection.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qprocessordetection.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qcompilerdetection.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qtypeinfo.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qtypetraits.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qsysinfo.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qlogging.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qflags.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qatomic.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qbasicatomic.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qatomic_bootstrap.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qgenericatomic.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qatomic_msvc.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qatomic_armv7.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qatomic_armv6.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qatomic_armv5.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qatomic_ia64.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qatomic_mips.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qatomic_x86.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qatomic_cxx11.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qatomic_gcc.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qatomic_unix.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qglobalstatic.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qmutex.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qnumeric.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o TetrisBlocks.o TetrisBlocks.cpp

TetrisGame.o: TetrisGame.cpp TetrisGame.h \
		/usr/local/software/qt-5.3.2/include/QtWidgets/QWidget \
		/usr/local/software/qt-5.3.2/include/QtWidgets/qwidget.h \
		/usr/local/software/qt-5.3.2/include/QtGui/qwindowdefs.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qglobal.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qconfig.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qfeatures.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qsystemdetection.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qprocessordetection.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qcompilerdetection.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qtypeinfo.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qtypetraits.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qsysinfo.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qlogging.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qflags.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qatomic.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qbasicatomic.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qatomic_bootstrap.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qgenericatomic.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qatomic_msvc.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qatomic_armv7.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qatomic_armv6.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qatomic_armv5.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qatomic_ia64.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qatomic_mips.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qatomic_x86.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qatomic_cxx11.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qatomic_gcc.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qatomic_unix.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qglobalstatic.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qmutex.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qnumeric.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qobjectdefs.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qnamespace.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qobjectdefs_impl.h \
		/usr/local/software/qt-5.3.2/include/QtGui/qwindowdefs_win.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qobject.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qstring.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qchar.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qbytearray.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qrefcount.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qarraydata.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qstringbuilder.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qlist.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qalgorithms.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qiterator.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qcoreevent.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qscopedpointer.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qmetatype.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qvarlengtharray.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qcontainerfwd.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qisenum.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qobject_impl.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qmargins.h \
		/usr/local/software/qt-5.3.2/include/QtGui/qpaintdevice.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qrect.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qsize.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qpoint.h \
		/usr/local/software/qt-5.3.2/include/QtGui/qpalette.h \
		/usr/local/software/qt-5.3.2/include/QtGui/qcolor.h \
		/usr/local/software/qt-5.3.2/include/QtGui/qrgb.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qstringlist.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qdatastream.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qiodevice.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qpair.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qregexp.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qstringmatcher.h \
		/usr/local/software/qt-5.3.2/include/QtGui/qbrush.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qvector.h \
		/usr/local/software/qt-5.3.2/include/QtGui/qmatrix.h \
		/usr/local/software/qt-5.3.2/include/QtGui/qpolygon.h \
		/usr/local/software/qt-5.3.2/include/QtGui/qregion.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qline.h \
		/usr/local/software/qt-5.3.2/include/QtGui/qtransform.h \
		/usr/local/software/qt-5.3.2/include/QtGui/qpainterpath.h \
		/usr/local/software/qt-5.3.2/include/QtGui/qimage.h \
		/usr/local/software/qt-5.3.2/include/QtGui/qpixmap.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qsharedpointer.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qshareddata.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qsharedpointer_impl.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qhash.h \
		/usr/local/software/qt-5.3.2/include/QtGui/qfont.h \
		/usr/local/software/qt-5.3.2/include/QtGui/qfontmetrics.h \
		/usr/local/software/qt-5.3.2/include/QtGui/qfontinfo.h \
		/usr/local/software/qt-5.3.2/include/QtWidgets/qsizepolicy.h \
		/usr/local/software/qt-5.3.2/include/QtGui/qcursor.h \
		/usr/local/software/qt-5.3.2/include/QtGui/qkeysequence.h \
		/usr/local/software/qt-5.3.2/include/QtGui/qevent.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qvariant.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qmap.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qdebug.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qtextstream.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qlocale.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qset.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qcontiguouscache.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qurl.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qurlquery.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qfile.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qfiledevice.h \
		/usr/local/software/qt-5.3.2/include/QtGui/qvector2d.h \
		/usr/local/software/qt-5.3.2/include/QtGui/qtouchdevice.h \
		/usr/local/software/qt-5.3.2/include/QtCore/QtCore \
		/usr/local/software/qt-5.3.2/include/QtCore/QtCoreDepends \
		/usr/local/software/qt-5.3.2/include/QtCore/qabstractanimation.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qanimationgroup.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qparallelanimationgroup.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qpauseanimation.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qpropertyanimation.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qvariantanimation.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qeasingcurve.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qsequentialanimationgroup.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qtextcodec.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qendian.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qlibraryinfo.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qdatetime.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qbuffer.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qdir.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qfileinfo.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qdiriterator.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qfileselector.h \
		/usr/local/software/qt-5.3.2/include/QtCore/QObject \
		/usr/local/software/qt-5.3.2/include/QtCore/QStringList \
		/usr/local/software/qt-5.3.2/include/QtCore/qfilesystemwatcher.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qlockfile.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qloggingcategory.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qprocess.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qresource.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qsavefile.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qsettings.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qstandardpaths.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qtemporarydir.h \
		/usr/local/software/qt-5.3.2/include/QtCore/QScopedPointer \
		/usr/local/software/qt-5.3.2/include/QtCore/qtemporaryfile.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qabstractitemmodel.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qabstractproxymodel.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qidentityproxymodel.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qitemselectionmodel.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qsortfilterproxymodel.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qstringlistmodel.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qjsonarray.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qjsonvalue.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qjsondocument.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qjsonobject.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qabstracteventdispatcher.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qeventloop.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qabstractnativeeventfilter.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qbasictimer.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qcoreapplication.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qmath.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qmetaobject.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qmimedata.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qobjectcleanuphandler.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qpointer.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qsharedmemory.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qsignalmapper.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qsocketnotifier.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qsystemsemaphore.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qtimer.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qtranslator.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qwineventnotifier.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qmimedatabase.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qmimetype.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qfactoryinterface.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qlibrary.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qplugin.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qpluginloader.h \
		/usr/local/software/qt-5.3.2/include/QtCore/quuid.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qabstractstate.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qabstracttransition.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qeventtransition.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qfinalstate.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qhistorystate.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qsignaltransition.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qstate.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qstatemachine.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qexception.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qfuture.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qfutureinterface.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qrunnable.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qresultstore.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qfuturesynchronizer.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qfuturewatcher.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qreadwritelock.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qsemaphore.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qthread.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qthreadpool.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qthreadstorage.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qwaitcondition.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qarraydataops.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qarraydatapointer.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qbitarray.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qbytearraymatcher.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qcache.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qcollator.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qcommandlineoption.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qcommandlineparser.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qcryptographichash.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qelapsedtimer.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qlinkedlist.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qmessageauthenticationcode.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qqueue.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qregularexpression.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qscopedvaluerollback.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qstack.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qtextboundaryfinder.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qtimeline.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qtimezone.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qxmlstream.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qtcoreversion.h \
		TetrisBlocks.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o TetrisGame.o TetrisGame.cpp

TetrisWindow.o: TetrisWindow.cpp TetrisWindow.h \
		/usr/local/software/qt-5.3.2/include/QtWidgets/QWidget \
		/usr/local/software/qt-5.3.2/include/QtWidgets/qwidget.h \
		/usr/local/software/qt-5.3.2/include/QtGui/qwindowdefs.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qglobal.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qconfig.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qfeatures.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qsystemdetection.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qprocessordetection.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qcompilerdetection.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qtypeinfo.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qtypetraits.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qsysinfo.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qlogging.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qflags.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qatomic.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qbasicatomic.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qatomic_bootstrap.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qgenericatomic.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qatomic_msvc.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qatomic_armv7.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qatomic_armv6.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qatomic_armv5.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qatomic_ia64.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qatomic_mips.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qatomic_x86.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qatomic_cxx11.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qatomic_gcc.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qatomic_unix.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qglobalstatic.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qmutex.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qnumeric.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qobjectdefs.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qnamespace.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qobjectdefs_impl.h \
		/usr/local/software/qt-5.3.2/include/QtGui/qwindowdefs_win.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qobject.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qstring.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qchar.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qbytearray.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qrefcount.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qarraydata.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qstringbuilder.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qlist.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qalgorithms.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qiterator.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qcoreevent.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qscopedpointer.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qmetatype.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qvarlengtharray.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qcontainerfwd.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qisenum.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qobject_impl.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qmargins.h \
		/usr/local/software/qt-5.3.2/include/QtGui/qpaintdevice.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qrect.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qsize.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qpoint.h \
		/usr/local/software/qt-5.3.2/include/QtGui/qpalette.h \
		/usr/local/software/qt-5.3.2/include/QtGui/qcolor.h \
		/usr/local/software/qt-5.3.2/include/QtGui/qrgb.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qstringlist.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qdatastream.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qiodevice.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qpair.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qregexp.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qstringmatcher.h \
		/usr/local/software/qt-5.3.2/include/QtGui/qbrush.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qvector.h \
		/usr/local/software/qt-5.3.2/include/QtGui/qmatrix.h \
		/usr/local/software/qt-5.3.2/include/QtGui/qpolygon.h \
		/usr/local/software/qt-5.3.2/include/QtGui/qregion.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qline.h \
		/usr/local/software/qt-5.3.2/include/QtGui/qtransform.h \
		/usr/local/software/qt-5.3.2/include/QtGui/qpainterpath.h \
		/usr/local/software/qt-5.3.2/include/QtGui/qimage.h \
		/usr/local/software/qt-5.3.2/include/QtGui/qpixmap.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qsharedpointer.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qshareddata.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qsharedpointer_impl.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qhash.h \
		/usr/local/software/qt-5.3.2/include/QtGui/qfont.h \
		/usr/local/software/qt-5.3.2/include/QtGui/qfontmetrics.h \
		/usr/local/software/qt-5.3.2/include/QtGui/qfontinfo.h \
		/usr/local/software/qt-5.3.2/include/QtWidgets/qsizepolicy.h \
		/usr/local/software/qt-5.3.2/include/QtGui/qcursor.h \
		/usr/local/software/qt-5.3.2/include/QtGui/qkeysequence.h \
		/usr/local/software/qt-5.3.2/include/QtGui/qevent.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qvariant.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qmap.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qdebug.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qtextstream.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qlocale.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qset.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qcontiguouscache.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qurl.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qurlquery.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qfile.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qfiledevice.h \
		/usr/local/software/qt-5.3.2/include/QtGui/qvector2d.h \
		/usr/local/software/qt-5.3.2/include/QtGui/qtouchdevice.h \
		/usr/local/software/qt-5.3.2/include/QtWidgets/QGridLayout \
		/usr/local/software/qt-5.3.2/include/QtWidgets/qgridlayout.h \
		/usr/local/software/qt-5.3.2/include/QtWidgets/qlayout.h \
		/usr/local/software/qt-5.3.2/include/QtWidgets/qlayoutitem.h \
		/usr/local/software/qt-5.3.2/include/QtWidgets/qboxlayout.h \
		/usr/local/software/qt-5.3.2/include/QtGui/QKeyEvent \
		/usr/local/software/qt-5.3.2/include/QtGui/QPainter \
		/usr/local/software/qt-5.3.2/include/QtGui/qpainter.h \
		/usr/local/software/qt-5.3.2/include/QtGui/qtextoption.h \
		/usr/local/software/qt-5.3.2/include/QtGui/qpen.h \
		/usr/local/software/qt-5.3.2/include/QtWidgets/QLabel \
		/usr/local/software/qt-5.3.2/include/QtWidgets/qlabel.h \
		/usr/local/software/qt-5.3.2/include/QtWidgets/qframe.h \
		/usr/local/software/qt-5.3.2/include/QtCore/QBasicTimer \
		/usr/local/software/qt-5.3.2/include/QtCore/qbasictimer.h \
		/usr/local/software/qt-5.3.2/include/QtCore/QString \
		TetrisGame.h \
		/usr/local/software/qt-5.3.2/include/QtCore/QtCore \
		/usr/local/software/qt-5.3.2/include/QtCore/QtCoreDepends \
		/usr/local/software/qt-5.3.2/include/QtCore/qabstractanimation.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qanimationgroup.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qparallelanimationgroup.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qpauseanimation.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qpropertyanimation.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qvariantanimation.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qeasingcurve.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qsequentialanimationgroup.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qtextcodec.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qendian.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qlibraryinfo.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qdatetime.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qbuffer.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qdir.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qfileinfo.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qdiriterator.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qfileselector.h \
		/usr/local/software/qt-5.3.2/include/QtCore/QObject \
		/usr/local/software/qt-5.3.2/include/QtCore/QStringList \
		/usr/local/software/qt-5.3.2/include/QtCore/qfilesystemwatcher.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qlockfile.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qloggingcategory.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qprocess.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qresource.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qsavefile.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qsettings.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qstandardpaths.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qtemporarydir.h \
		/usr/local/software/qt-5.3.2/include/QtCore/QScopedPointer \
		/usr/local/software/qt-5.3.2/include/QtCore/qtemporaryfile.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qabstractitemmodel.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qabstractproxymodel.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qidentityproxymodel.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qitemselectionmodel.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qsortfilterproxymodel.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qstringlistmodel.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qjsonarray.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qjsonvalue.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qjsondocument.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qjsonobject.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qabstracteventdispatcher.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qeventloop.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qabstractnativeeventfilter.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qcoreapplication.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qmath.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qmetaobject.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qmimedata.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qobjectcleanuphandler.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qpointer.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qsharedmemory.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qsignalmapper.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qsocketnotifier.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qsystemsemaphore.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qtimer.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qtranslator.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qwineventnotifier.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qmimedatabase.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qmimetype.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qfactoryinterface.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qlibrary.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qplugin.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qpluginloader.h \
		/usr/local/software/qt-5.3.2/include/QtCore/quuid.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qabstractstate.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qabstracttransition.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qeventtransition.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qfinalstate.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qhistorystate.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qsignaltransition.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qstate.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qstatemachine.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qexception.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qfuture.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qfutureinterface.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qrunnable.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qresultstore.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qfuturesynchronizer.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qfuturewatcher.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qreadwritelock.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qsemaphore.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qthread.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qthreadpool.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qthreadstorage.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qwaitcondition.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qarraydataops.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qarraydatapointer.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qbitarray.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qbytearraymatcher.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qcache.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qcollator.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qcommandlineoption.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qcommandlineparser.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qcryptographichash.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qelapsedtimer.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qlinkedlist.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qmessageauthenticationcode.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qqueue.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qregularexpression.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qscopedvaluerollback.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qstack.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qtextboundaryfinder.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qtimeline.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qtimezone.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qxmlstream.h \
		/usr/local/software/qt-5.3.2/include/QtCore/qtcoreversion.h \
		TetrisBlocks.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o TetrisWindow.o TetrisWindow.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

