######################################################################
# Automatically generated by qmake (3.0) Mon Sep 26 15:52:27 2016
######################################################################

TEMPLATE = app
TARGET = Project2
INCLUDEPATH += .
QT += widgets

# Input
HEADERS += TetrisBlocks.h TetrisGame.h TetrisWindow.h
SOURCES += main.cpp TetrisWindow.cpp
