######################################################################
# Automatically generated by qmake (3.0) Sun Oct 2 14:52:55 2016
######################################################################

QT += widgets
TEMPLATE = app
TARGET = QtTimerTryout
INCLUDEPATH += .

# Input
HEADERS += MyWindow.h
SOURCES += main.cpp MyWindow.cpp
